export const LIST_SEXUAL_ORIENTATION = "LIST_SEXUAL_ORIENTATION";
export const LIST_GENDERS = "LIST_GENDERS";
export const LIST_LANGUAGES = "LIST_LANGUAGES";
export const LIST_ETHNICITY = "LIST_ETHNICITY";
export const LIST_CHILDREN_STATUS = "LIST_CHILDREN_STATUS";
export const LIST_WANT_CHILDREN_STATUS = "LIST_WANT_CHILDREN_STATUS";
export const LIST_RELIGIONS = "LIST_RELIGIONS";
export const LIST_EDUCATION_LEVELS = "LIST_EDUCATION_LEVELS";
